pygments: true
exclude:
  - Rakefile
  - README.markdown
  - CNAME
url: http://kungfudiscomonkey.net
title: KungFuDiscoMonkey.net
permalink: /:categories/:title.html
timezone: America/Los_Angeles
markdown: redcarpet