highlighter: true
exclude:
  - Rakefile
  - README.markdown
  - CNAME
url: http://paultraylor.net
title: KungFuDiscoMonkey.net
permalink: /:categories/:title.html
timezone: Asia/Tokyo
markdown: kramdown
twitter_username: kfdm
github_username:  kfdm
