exclude:
  - README.md
  - CNAME
url: http://paultraylor.net
name: KungFuDiscoMonkey.net
permalink: /:categories/:title.html
timezone: Asia/Tokyo
markdown: kramdown
twitter_username: kfdm
github_username:  kfdm

author:
  name: Paul Traylor

feed:
  path: atom.xml

defaults:
  -
    scope:
      path: "blog"
    values:
      section: about
  -
    scope:
      path: "nihongo"
    values:
      section: future
      lang: ja

gems:
  - jekyll-feed
  - jekyll-redirect-from
