exclude:
  - CNAME
  - Gemfile*
  - Makefile
  - README.md
include:
  - .well-known
url: https://paultraylor.net
name: Paul Traylor
permalink: /:categories/:title.html
timezone: Asia/Tokyo
markdown: kramdown
twitter_username: kfdm
github_username:  kfdm

author:
  name: Paul Traylor

feed:
  path: atom.xml

defaults:
  -
    scope:
      path: "blog"
    values:
      section: about
      permalink: /:categories/:title.html
  -
    scope:
      path: "nihongo"
    values:
      section: future
      lang: ja
      permalink: /:categories/:title.html
  -
    scope:
      path: ""
      type: tag_index
    values:
      layout: "tag.index"


collections:
  tag_index:
    output: true

plugins:
  - jekyll-feed
  - jekyll-redirect-from
