exclude:
  - README.md
  - CNAME
url: http://paultraylor.net
title: KungFuDiscoMonkey.net
permalink: /:categories/:title.html
timezone: Asia/Tokyo
markdown: kramdown
twitter_username: kfdm
github_username:  kfdm

defaults:
  -
    scope:
      path: "blog"
      type: "posts"
    values:
      section: about
  -
    scope:
      path: "nihongo"
      type: "posts"
    values:
      section: future

gems:
  - jekyll-redirect-from
